### ISSUE TITLE
Request: Example for ESP32

### ISSUE THREAD

**Issue by LuckyLuzz** [nzbart/ArlecRC210Switch#1]
Hey,
nice lib! I was wondering if you could provide an general example sketch and and maybe one for a ESP32?

**Comment by nzbart** [comment]
There's some sample code in the [Readme](https://github.com/nzbart/ArlecRC210Switch#sample-code), which should also work on the ESP32 if you're using the Arduino platform. 

What in particular are you looking for that's not clear from the "blink" style example?
